Data manipulator
1sputnik/pasteuriser-ai-assistant pull request #25
Opened 2024-01-23 07:17 UTC by Lenonim

Вынесение модуля для обработки данных как отдельную программу.

2024-02-10 15:04 UTC, Lenonim commented
результаты визуализации
![image](https://github.com/1sputnik/pasteuriser-ai-assistant/assets/82272778/dfd4a7a6-7590-4cc1-bcb5-77cbb37ef29e)
![image](https://github.com/1sputnik/pasteuriser-ai-assistant/assets/82272778/d5acb49c-d98d-47e8-a4d0-e8d02c1c5f08)

2024-02-10 15:26 UTC, Lenonim commented
соединил первый и второй сид и визуализировал
![image](https://github.com/1sputnik/pasteuriser-ai-assistant/assets/82272778/20dc1e18-fa89-48c0-94f7-433f9a94acb6)

2024-02-14 20:19 UTC, Lenonim commented
вид табличного формата в csv файле:
![image](https://github.com/1sputnik/pasteuriser-ai-assistant/assets/82272778/a78abc5d-a501-418d-b6fd-04f788387745)

2024-02-17 20:32 UTC, Lenonim commented
визуализация табличного формата:
![image](https://github.com/1sputnik/pasteuriser-ai-assistant/assets/82272778/0fb65fd0-bb41-4382-94f2-ddb3f1380920)

2024-02-18 09:50 UTC, Lenonim commented
пример графиков с одним сидом:
![image](https://github.com/1sputnik/pasteuriser-ai-assistant/assets/82272778/4287e2b8-49ef-426a-ac16-8cb10592277b)
со всеми сидами:
![image](https://github.com/1sputnik/pasteuriser-ai-assistant/assets/82272778/26024cc1-d3b8-4c5a-a55c-87e54e3e762e)
с избранными сидами (нп с двумя сидами):
![image](https://github.com/1sputnik/pasteuriser-ai-assistant/assets/82272778/0ffdeeaf-3b53-4eaf-a2ef-d582932fa7b9)

2024-02-18 09:51 UTC, Lenonim commented
@idzm 
Необходимо принятие пул реквеста для продолжения работы

2024-02-21 07:20 UTC, idzm requested changes
Кодировка файлов должна быть **UTF-8**.

2024-02-22 16:45 UTC, Lenonim commented
@idzm 
кодировка файлов исправлена.

2024-03-26 17:43 UTC, Lenonim commented
@idzm 
Завершил документацию по DataManipulator

2024-12-26 13:47 UTC, idzm approved these changes

2024-12-26 13:47 UTC, merged